Front/routes/web.php
    Route::put('catalogues/housing/rooms/{room}',['as' => 'housing.rooms.update', 'uses' => 'Admin\HousingRoomController@update']);
    Route::delete('catalogues/housing/rooms/{room}',['as' => 'housing.rooms.destroy', 'uses' => 'Admin\HousingRoomController@destroy']);
    Route::put('catalogues/housing/rooms/{room}/activate',['as' => 'housing.rooms.activate', 'uses' => 'Admin\HousingRoomController@activate']);

    // Housing room package
    Route::get('catalogues/housing/rooms/{room}/packages',['as' => 'housing.rooms.packages.index', 'uses' => 'Admin\HousingRoomPackageController@index']);
    Route::post('catalogues/housing/rooms/{room}/packages',['as' => 'housing.rooms.packages.store', 'uses' => 'Admin\HousingRoomPackageController@store']);
    Route::get('catalogues/housing/rooms/{room}/packages/create',['as' => 'housing.rooms.packages.create', 'uses' => 'Admin\HousingRoomPackageController@create']);
    Route::get('catalogues/housing/rooms/packages/{housingRoomPackage}',['as' => 'housing.rooms.packages.show', 'uses' => 'Admin\HousingRoomPackageController@show']);
    Route::get('catalogues/housing/rooms/packages/{housingRoomPackage}/edit',['as' => 'housing.rooms.packages.edit', 'uses' => 'Admin\HousingRoomPackageController@edit']);
    Route::put('catalogues/housing/rooms/packages/{housingRoomPackage}',['as' => 'housing.rooms.packages.update', 'uses' => 'Admin\HousingRoomPackageController@update']);
    Route::delete('catalogues/housing/rooms/packages/{housingRoomPackage}',['as' => 'housing.rooms.packages.destroy', 'uses' => 'Admin\HousingRoomPackageController@destroy']);
    Route::put('catalogues/housing/rooms/packages/{housingRoomPackage}/activate',['as' => 'housing.rooms.packages.activate', 'uses' => 'Admin\HousingRoomPackageController@activate']);

    Route::get('reports/{report}', ['as' => 'reports.index',  'uses' => 'Admin\ReportController@index']);
    Route::post('reports/export', ['as' => 'reports.export',  'uses' => 'Admin\ReportController@exportToPDF']);
    Route::resource('users', 'Admin\UserController');

    Route::resource('groups', 'Admin\GroupController');
    Route::resource('schedules', 'Admin\ScheduleController');
    Route::post('schedules/print', ['as' => 'schedules.print', 'uses' => 'Admin\ScheduleController@print']);
    Route::post('schedules/export/csv', ['as' => 'schedules.csv', 'uses' => 'Admin\ScheduleController@exportToCsv']);

    Route::get('import', ['as' => 'import.index', 'uses' => 'Admin\ImportController@index']);
    Route::post('import', ['as' => 'import.store', 'uses' => 'Admin\ImportController@store']);
    Route::get('import/{id}', ['as' => 'import.show', 'uses' => 'Admin\ImportController@show']);

    // Centro de consumo
    Route::resource('consumption-centers', 'Admin\ConsumptionCenterController');
    Route::put('consumption-centers/{consumptionCenter}/activate', ['as' => 'consumption-centers.activate', 'uses' => 'Admin\ConsumptionCenterController@activate']);

    // Caja chica
    Route::resource('petty-cashes', 'Admin\PettyCashController');
    Route::post('petty-cashes/export/csv', ['as' => 'petty-cashes.csv', 'uses' => 'Admin\PettyCashController@exportToCsv']);

    // Room-types
    Route::get('catalogues/room-types', ['as' => 'room-types.index', 'uses' => 'Admin\RoomTypeController@index']);
    Route::get('catalogues/room-types/create', ['as' => 'room-types.create', 'uses' => 'Admin\RoomTypeController@create']);
    Route::post('catalogues/room-types', ['as' => 'room-types.store', 'uses' => 'Admin\RoomTypeController@store']);
    Route::get('catalogues/room-types/{roomType}', ['as' => 'room-types.show', 'uses' => 'Admin\RoomTypeController@show']);
    Route::get('catalogues/room-types/{roomType}/edit', ['as' => 'room-types.edit', 'uses' => 'Admin\RoomTypeController@edit']);
    Route::put('catalogues/room-types/{roomType}', ['as' => 'room-types.update', 'uses' => 'Admin\RoomTypeController@update']);
    Route::delete('catalogues/room-types/{roomType}', ['as' => 'room-types.destroy', 'uses' => 'Admin\RoomTypeController@destroy']);
    Route::put('catalogues/room-types/{roomType}/activate', ['as' => 'room-types.activate', 'uses' => 'Admin\RoomTypeController@activate']);

    // Countries
    Route::get('catalogues/countries', ['as' => 'countries.index', 'uses' => 'Admin\CountryController@index']);
    Route::get('catalogues/countries/create', ['as' => 'countries.create', 'uses' => 'Admin\CountryController@create']);
    Route::post('catalogues/countries', ['as' => 'countries.store', 'uses' => 'Admin\CountryController@store']);
    Route::get('catalogues/countries/{country}', ['as' => 'countries.show', 'uses' => 'Admin\CountryController@show']);
    Route::get('catalogues/countries/{country}/edit', ['as' => 'countries.edit', 'uses' => 'Admin\CountryController@edit']);
    Route::put('catalogues/countries/{country}', ['as' => 'countries.update', 'uses' => 'Admin\CountryController@update']);
    Route::delete('catalogues/countries/{country}', ['as' => 'countries.destroy', 'uses' => 'Admin\CountryController@destroy']);
    Route::put('catalogues/countries/{country}/activate', ['as' => 'countries.activate', 'uses' => 'Admin\CountryController@activate']);
    Route::put('catalogues/countries/{country}/sort', ['as' => 'countries.sort', 'uses' => 'Admin\CountryController@sort']);

    // Courses
    Route::resource('catalogues/courses', 'Admin\CourseController');
    Route::put('catalogues/courses/{package}/activate', ['as' => 'courses.activate', 'uses' => 'Admin\CourseController@activate']);

    // Experiences
    Route::post('catalogues/experiences', ['as' => 'experiences.store', 'uses' => 'Admin\ExperienceController@store']);
    Route::get('catalogues/experiences/create', ['as' => 'experiences.create', 'uses' => 'Admin\ExperienceController@create']);

    // People
    Route::get('catalogues/people', ['as' => 'people.index', 'uses' => 'Admin\PersonController@index']);
    Route::get('catalogues/people/create', ['as' => 'people.create', 'uses' => 'Admin\PersonController@create']);
    Route::post('catalogues/people', ['as' => 'people.store', 'uses' => 'Admin\PersonController@store']);
    Route::get('catalogues/people/{person}', ['as' => 'people.show', 'uses' => 'Admin\PersonController@show']);
    Route::get('catalogues/people/{person}/edit', ['as' => 'people.edit', 'uses' => 'Admin\PersonController@edit']);
    Route::put('catalogues/people/{person}', ['as' => 'people.update', 'uses' => 'Admin\PersonController@update']);
    Route::delete('catalogues/people/{person}', ['as' => 'people.destroy', 'uses' => 'Admin\PersonController@destroy']);

    // Places
    Route::get('catalogues/places', ['as' => 'places.index', 'uses' => 'Admin\PlaceController@index']);
    Route::get('catalogues/places/create', ['as' => 'places.create', 'uses' => 'Admin\PlaceController@create']);
    Route::post('catalogues/places', ['as' => 'places.store', 'uses' => 'Admin\PlaceController@store']);
    Route::get('catalogues/places/{place}', ['as' => 'places.show', 'uses' => 'Admin\PlaceController@show']);
    Route::get('catalogues/places/{place}/edit', ['as' => 'places.edit', 'uses' => 'Admin\PlaceController@edit']);
    Route::put('catalogues/places/{place}', ['as' => 'places.update', 'uses' => 'Admin\PlaceController@update']);
    Route::delete('catalogues/places/{place}', ['as' => 'places.destroy', 'uses' => 'Admin\PlaceController@destroy']);

    // Residences
    Route::resource('catalogues/residences', 'Admin\ResidenceController');

    // Rooms
    Route::resource("catalogues/residences/{residence}/rooms", "Admin\RoomController");

    // Roles
    Route::put("roles/{role}/activate", ['as' => 'roles.activate', 'uses' => "Admin\RoleController@activate"]);
    Route::resource("roles", "Admin\RoleController");

    // Moneda
    Route::get('currencies', ['as' => 'currencies.index', 'uses' => 'Admin\CurrencyController@index']);
    Route::get('currencies/create', ['as' => 'currencies.create', 'uses' => 'Admin\CurrencyController@create']);
    Route::post('currencies', ['as' => 'currencies.store', 'uses' => 'Admin\CurrencyController@store']);
    Route::get('currencies/{id}', ['as' => 'currencies.show', 'uses' => 'Admin\CurrencyController@show']);
    Route::get('currencies/{id}/edit', ['as' => 'currencies.edit', 'uses' => 'Admin\CurrencyController@edit']);
    Route::put('currencies/{id}', ['as' => 'currencies.update', 'uses' => 'Admin\CurrencyController@update']);
    Route::delete('currencies/{id}', ['as' => 'currencies.destroy', 'uses' => 'Admin\CurrencyController@destroy']);
});

// public
Route::group(['middleware' => ['auth_client']], function() {
    Route::get('booking', ['as' => 'public.bookings.index', 'uses' => 'BookingController@index']);
    Route::post('booking', ['as' => 'public.bookings.store', 'uses' => 'BookingController@store']);
    Route::get('booking/payment', ['as' => 'public.bookings.payment', 'uses' => 'BookingController@payment']);
    // Pay with conekta
    Route::post('booking/payment', ['as' => 'public.bookings.process_payment', 'uses' => 'BookingController@processPayment']);
    // Personal information
    Route::get('booking/your-info', ['as' => 'public.bookings.your-info', 'uses' => 'BookingController@personalInfo']);
    Route::post('booking/storeClient', ['as' => 'public.bookings.store-client', 'uses' => 'BookingController@storeClient']);
    // Paypal
    Route::post('paypal', array('as' => 'paypal.payment','uses' => 'PaypalController@createPayment',));
    Route::get('paypal', array('as' => 'paypal.execute','uses' => 'PaypalController@executePayment',));
    // Housing
    Route::get('housing/availability', ['as' => 'housing.availability', 'uses' => 'Admin\HousingController@availability']);
    Route::get('housing/occupancy', ['as' => 'housing.occupancy', 'uses' => 'Admin\HousingController@occupancy']);

    // Cancellation policies
    Route::get('cancellation-policies', function()
    {
        return view('cancellation-policies.index');

Front/app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Helpers\Constant;
use Validator;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $title = 'Roles';
        $url = 'api/v1/roles';
        $params = $this->prepareParams($request, ['page']);

        $roles = $this->get($url . '?' . make_url_params($params), $request);

        return view('roles.index')
            ->with(compact(
                'title',
                'roles'
            ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $title = 'Edit Role';
        $formType = Constant::FORM_CREATE;
        $formAction = route('roles.store');

        $modules = $this->get("api/v1/system-modules?include=permissions&order=id&dir=asc", $request);
        $accessesTo = [];

        return view('roles.form')
            ->with(compact(
                'title',
                'formType',
                'formAction',
                'accessesTo',
                'modules'
            ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = [];
        $validator = Validator::make([], []);
        $data['name'] = $request->get('name');
        $accesses = $request->get('accesses');
        if ($accesses == null) {
            $accesses = array();
        } else {
            $accessesTmp = [];
            foreach ($accesses as $key => $modules) {
                $permissionModule = [];
                foreach ($modules as $key2 => $permission) {
                    $permissionModule[] = [
                        'id' => $permission
                    ];
                }
                // Poner el array en el formato que el API pueda leerlo
                $accessesTmp[] = [
                    'module_id' => $key,
                    'permissions' => $permissionModule
                ];
            }
            $accesses = $accessesTmp;
        }
        $data['accesses'] = $accesses;

        $response = $this->post("api/v1/roles", $data, $request);
        $request->session()->flash('response', [
            'status_code' => $response->status_code,
            'message' => $response->message
        ]);

        if ($response->status_code != 200 && $response->status_code != 201) {
            if (isset($response->errors)) {
                foreach ($response->errors as $key => $messages) {
                    foreach ($messages as $msg) {
                        $validator->errors()->add($key, $msg);
                    }
                }
            }
            return redirect()
                    ->back()
                    ->withInput()
                    ->withErrors($validator);
        }
        return redirect()->route('roles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $title = 'Edit Role';
        $formType = Constant::FORM_EDIT;
        $formAction = route('roles.update', ['id' => $id]);

        $role = $this->get("api/v1/roles/$id?include=accesses", $request);
        $modules = $this->get("api/v1/system-modules?include=permissions&order=id&dir=asc", $request);

        $accessesTo = [];
        foreach(isset($role->data->accesses->data) ? $role->data->accesses->data : [] as $a) {
            $accessesTo[$a->module->data->id] = collect($a->permissions->data)->pluck('id')->toArray();
        };

        return view('roles.form')
            ->with(compact(
                'title',
                'formType',
                'formAction',
                'role',
                'modules',
                'accessesTo'
            ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make([], []);
        $data = [];
        $data['updated_at'] = $request->get('updated_at');
        $data['name'] = $request->get('name');
        $accesses = $request->get('accesses');
        if ($accesses == null) {
            $accesses = array();
        } else {
            $accessesTmp = [];
            foreach ($accesses as $key => $modules) {
                $permissionModule = [];
                foreach ($modules as $key2 => $permission) {
                    $permissionModule[] = [
                        'id' => $permission
                    ];
                }
                // Poner el array en el formato que el API pueda leerlo
                $accessesTmp[] = [
                    'module_id' => $key,
                    'permissions' => $permissionModule
                ];
            }
            $accesses = $accessesTmp;
        }
        $data['accesses'] = $accesses;
        $response = $this->put("api/v1/roles/$id", $data, $request);
        $request->session()->flash('response', [
            'status_code' => $response->status_code,
            'message' => $response->message
        ]);
        if ($response->status_code != 200) {
            if (isset($response->errors)) {
                foreach ($response->errors as $key => $messages) {
                    foreach ($messages as $msg) {
                        $validator->errors()->add($key, $msg);
                    }
                }
            }
            return redirect()
                ->back()
                ->withInput()
                ->withErrors($validator);
        }
        return redirect()->route('roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $response = $this->delete("api/v1/roles/$id", $request);
        $request->session()->flash('response', [
            'status_code' => $response->status_code,
            'message' => $response->message
        ]);
        return redirect()->back();
    }

    /**
     * Activate / deactivate the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function activate(Request $request, $id)
    {
        $response = $this->put("api/v1/roles/$id/activate", [], $request);
        $request->session()->flash('response', [
            'status_code' => $response->status_code,
            'message' => $response->message
        ]);
        return redirect()->route('roles.index');
    }
}

Front/resources/views/roles/form.blade.php
@extends('layouts.app')

@section('title', $title)

@section('content-header')
    <h1>{{ $title }}</h1>
@endsection

@section('content')
    <form action="{{ $formAction }}" method="post">
        {{ csrf_field() }}
        @if ($formType === Constant::FORM_EDIT)
            {{ method_field('PUT') }}
            <input type="hidden" name="updated_at" value="{{ $role->data->updated_at }}" />
        @endif
        <div class="box">
            <div class="box-header">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                            <label for="name" class="control-label">Role name</label>
                            <input type="text" name="name" id="name" class="form-control" required
                                value="{{ old('name') ? old('name') : (isset($role->data->name) ? $role->data->name : '') }}">
                            <span class="help-block">{{ $errors->first('name') }}</span>
                        </div>
                    </div>
                </div>
                <hr>
            </div>

            <div class="box-body">
                <div class="row">
                    <div class="col-xs-12">
                        @php
                            if (old('accesses')) {
                                $accessesTo = old('accesses');
                            }
                            $moduleExist = false;
                        @endphp
                        @forelse ($modules->data as $module)
                            @php
                                $moduleExist = array_key_exists($module->id, $accessesTo);
                            @endphp
                            <div>
                                <strong>{{ $module->name }}</strong>
                                <ul class="list-inline">
                                    @foreach ($module->permissions->data as $permission)
                                        <li>
                                            <div class="checkbox iCheck">
                                                <label>
                                                    <input type="checkbox" id="{{ $permission->id }}" name="accesses[{{ $module->id }}][]" value="{{ $permission->id }}"
                                                        {{ $moduleExist ? (in_array($permission->id, $accessesTo[$module->id]) ? 'checked' : '') : '' }}>
                                                    {{ $permission->name }}
                                                </label>
                                            </div>
                                        </li>
                                    @endforeach
                                </ul>
                            </div>
                        @empty
                            <span class="no-data">No data available.</span>
                        @endforelse
                    </div>
                </div>
            </div>
        </div>

        <a href="{{ url()->previous() }}" type="cancel" class="btn btn-default">Cancel</a>
        <button type="submit" class="btn btn-primary">Save</button>
</form>
 @endsection

Front/resources/views/roles/index.blade.php
@extends('layouts.app')

@section('title', $title)

@section('content-header')
    <h1>{{ $title }}</h1>
@endsection

@section('content')
    <div class="box">
        <div class="box-header with-border">
            <a href="{{ route('roles.create') }}" class="btn btn-primary pull-right">New role</a>
        </div>
        <div class="box-body">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Role</th>
                        <th class="text-center fit">Status</th>
                        <th class="text-center fit">Edit</th>
                        <th class="text-center fit">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($roles->data as $role)
                        <tr>
                            <td>{{ $role->name }}</td>
                            <td class="text-center fit">
                                <form action="{{ route('roles.activate', [ 'id' => $role->id]) }}" method="post">
                                    {{ csrf_field() }}
                                    {{ method_field('PUT') }}
                                    <button type="submit" class="action-btn table-btn-activate" style="opacity: 1;" title="{{ $role->is_active == 1? 'Deactivate' : 'Activate' }}">
                                        <i class="fa fa-flag {{ $role->is_active == 1 ? 'on' : 'off' }}" aria-hidden="true"></i>
                                    </button>
                                </form>
                            </td>
                            <td class="text-center fit">
                                <a class="action-btn" href="{{ route('roles.edit', ['id' => $role->id]) }}">
                                    <i class="fa fa-pencil" aria-hidden="true"></i>
                                </a>
                            </td>
                            <td class="text-center fit">
                                <form action="{{ route('roles.destroy', [ 'id' => $role->id]) }}" method="post">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <button type="submit" class="action-btn table-btn-destroy">
                                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="100">No data available</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('scripts')
    @parent
    <script>
            $(function() {
                EXP.initConfirmButton({
                    selector: 'button.table-btn-activate',
                    title: "Activate/deactivate role",
                    msg: "This action is going to activate/deactivate the current role.",
                    callback: function(btn) {
                        $(btn).parent().submit();
                    }
                });
                
                EXP.initConfirmButton({
                    selector: 'button.table-btn-destroy',
                    title: "Delete role",
                    msg: "This action is going to delete the current role.",
                    callback: function(btn) {
                        $(btn).parent().submit();
                    }
                });
            });
    </script>
@endsection