Front/routes/web.php
    Route::get('catalogues/housing/{housing}/rooms',['as' => 'housing.rooms.index', 'uses' => 'Admin\HousingRoomController@index']);
    Route::post('catalogues/housing/{housing}/rooms',['as' => 'housing.rooms.store', 'uses' => 'Admin\HousingRoomController@store']);
    Route::get('catalogues/housing/{housing}/rooms/create',['as' => 'housing.rooms.create', 'uses' => 'Admin\HousingRoomController@create']);
    Route::get('catalogues/housing/rooms/{room}',['as' => 'housing.rooms.show', 'uses' => 'Admin\HousingRoomController@show']);
    Route::get('catalogues/housing/rooms/{room}/edit',['as' => 'housing.rooms.edit', 'uses' => 'Admin\HousingRoomController@edit']);
    Route::put('catalogues/housing/rooms/{room}',['as' => 'housing.rooms.update', 'uses' => 'Admin\HousingRoomController@update']);
    Route::delete('catalogues/housing/rooms/{room}',['as' => 'housing.rooms.destroy', 'uses' => 'Admin\HousingRoomController@destroy']);
    Route::put('catalogues/housing/rooms/{room}/activate',['as' => 'housing.rooms.activate', 'uses' => 'Admin\HousingRoomController@activate']);

    // Housing room package
    Route::get('catalogues/housing/rooms/{room}/packages',['as' => 'housing.rooms.packages.index', 'uses' => 'Admin\HousingRoomPackageController@index']);
    Route::post('catalogues/housing/rooms/{room}/packages',['as' => 'housing.rooms.packages.store', 'uses' => 'Admin\HousingRoomPackageController@store']);
    Route::get('catalogues/housing/rooms/{room}/packages/create',['as' => 'housing.rooms.packages.create', 'uses' => 'Admin\HousingRoomPackageController@create']);
    Route::get('catalogues/housing/rooms/packages/{housingRoomPackage}',['as' => 'housing.rooms.packages.show', 'uses' => 'Admin\HousingRoomPackageController@show']);
    Route::get('catalogues/housing/rooms/packages/{housingRoomPackage}/edit',['as' => 'housing.rooms.packages.edit', 'uses' => 'Admin\HousingRoomPackageController@edit']);
    Route::put('catalogues/housing/rooms/packages/{housingRoomPackage}',['as' => 'housing.rooms.packages.update', 'uses' => 'Admin\HousingRoomPackageController@update']);
    Route::delete('catalogues/housing/rooms/packages/{housingRoomPackage}',['as' => 'housing.rooms.packages.destroy', 'uses' => 'Admin\HousingRoomPackageController@destroy']);
    Route::put('catalogues/housing/rooms/packages/{housingRoomPackage}/activate',['as' => 'housing.rooms.packages.activate', 'uses' => 'Admin\HousingRoomPackageController@activate']);

    Route::get('reports/{report}', ['as' => 'reports.index',  'uses' => 'Admin\ReportController@index']);
    Route::post('reports/export', ['as' => 'reports.export',  'uses' => 'Admin\ReportController@exportToPDF']);
    Route::resource('users', 'Admin\UserController');

    Route::resource('groups', 'Admin\GroupController');
    Route::resource('schedules', 'Admin\ScheduleController');
    Route::post('schedules/print', ['as' => 'schedules.print', 'uses' => 'Admin\ScheduleController@print']);
    Route::post('schedules/export/csv', ['as' => 'schedules.csv', 'uses' => 'Admin\ScheduleController@exportToCsv']);

    Route::get('import', ['as' => 'import.index', 'uses' => 'Admin\ImportController@index']);
    Route::post('import', ['as' => 'import.store', 'uses' => 'Admin\ImportController@store']);
    Route::get('import/{id}', ['as' => 'import.show', 'uses' => 'Admin\ImportController@show']);

    // Centro de consumo
    Route::resource('consumption-centers', 'Admin\ConsumptionCenterController');
    Route::put('consumption-centers/{consumptionCenter}/activate', ['as' => 'consumption-centers.activate', 'uses' => 'Admin\ConsumptionCenterController@activate']);

    // Caja chica
    Route::resource('petty-cashes', 'Admin\PettyCashController');
    Route::post('petty-cashes/export/csv', ['as' => 'petty-cashes.csv', 'uses' => 'Admin\PettyCashController@exportToCsv']);

    // Room-types
    Route::get('catalogues/room-types', ['as' => 'room-types.index', 'uses' => 'Admin\RoomTypeController@index']);
    Route::get('catalogues/room-types/create', ['as' => 'room-types.create', 'uses' => 'Admin\RoomTypeController@create']);
    Route::post('catalogues/room-types', ['as' => 'room-types.store', 'uses' => 'Admin\RoomTypeController@store']);
    Route::get('catalogues/room-types/{roomType}', ['as' => 'room-types.show', 'uses' => 'Admin\RoomTypeController@show']);
    Route::get('catalogues/room-types/{roomType}/edit', ['as' => 'room-types.edit', 'uses' => 'Admin\RoomTypeController@edit']);
    Route::put('catalogues/room-types/{roomType}', ['as' => 'room-types.update', 'uses' => 'Admin\RoomTypeController@update']);
    Route::delete('catalogues/room-types/{roomType}', ['as' => 'room-types.destroy', 'uses' => 'Admin\RoomTypeController@destroy']);
    Route::put('catalogues/room-types/{roomType}/activate', ['as' => 'room-types.activate', 'uses' => 'Admin\RoomTypeController@activate']);

    // Countries
    Route::get('catalogues/countries', ['as' => 'countries.index', 'uses' => 'Admin\CountryController@index']);
    Route::get('catalogues/countries/create', ['as' => 'countries.create', 'uses' => 'Admin\CountryController@create']);
    Route::post('catalogues/countries', ['as' => 'countries.store', 'uses' => 'Admin\CountryController@store']);
    Route::get('catalogues/countries/{country}', ['as' => 'countries.show', 'uses' => 'Admin\CountryController@show']);
    Route::get('catalogues/countries/{country}/edit', ['as' => 'countries.edit', 'uses' => 'Admin\CountryController@edit']);
    Route::put('catalogues/countries/{country}', ['as' => 'countries.update', 'uses' => 'Admin\CountryController@update']);
    Route::delete('catalogues/countries/{country}', ['as' => 'countries.destroy', 'uses' => 'Admin\CountryController@destroy']);
    Route::put('catalogues/countries/{country}/activate', ['as' => 'countries.activate', 'uses' => 'Admin\CountryController@activate']);
    Route::put('catalogues/countries/{country}/sort', ['as' => 'countries.sort', 'uses' => 'Admin\CountryController@sort']);

    // Courses
    Route::resource('catalogues/courses', 'Admin\CourseController');
    Route::put('catalogues/courses/{package}/activate', ['as' => 'courses.activate', 'uses' => 'Admin\CourseController@activate']);

    // Experiences
    Route::post('catalogues/experiences', ['as' => 'experiences.store', 'uses' => 'Admin\ExperienceController@store']);
    Route::get('catalogues/experiences/create', ['as' => 'experiences.create', 'uses' => 'Admin\ExperienceController@create']);

    // People
    Route::get('catalogues/people', ['as' => 'people.index', 'uses' => 'Admin\PersonController@index']);
    Route::get('catalogues/people/create', ['as' => 'people.create', 'uses' => 'Admin\PersonController@create']);
    Route::post('catalogues/people', ['as' => 'people.store', 'uses' => 'Admin\PersonController@store']);
    Route::get('catalogues/people/{person}', ['as' => 'people.show', 'uses' => 'Admin\PersonController@show']);
    Route::get('catalogues/people/{person}/edit', ['as' => 'people.edit', 'uses' => 'Admin\PersonController@edit']);
    Route::put('catalogues/people/{person}', ['as' => 'people.update', 'uses' => 'Admin\PersonController@update']);
    Route::delete('catalogues/people/{person}', ['as' => 'people.destroy', 'uses' => 'Admin\PersonController@destroy']);

    // Places
    Route::get('catalogues/places', ['as' => 'places.index', 'uses' => 'Admin\PlaceController@index']);
    Route::get('catalogues/places/create', ['as' => 'places.create', 'uses' => 'Admin\PlaceController@create']);
    Route::post('catalogues/places', ['as' => 'places.store', 'uses' => 'Admin\PlaceController@store']);
    Route::get('catalogues/places/{place}', ['as' => 'places.show', 'uses' => 'Admin\PlaceController@show']);
    Route::get('catalogues/places/{place}/edit', ['as' => 'places.edit', 'uses' => 'Admin\PlaceController@edit']);
    Route::put('catalogues/places/{place}', ['as' => 'places.update', 'uses' => 'Admin\PlaceController@update']);
    Route::delete('catalogues/places/{place}', ['as' => 'places.destroy', 'uses' => 'Admin\PlaceController@destroy']);

    // Residences
    Route::resource('catalogues/residences', 'Admin\ResidenceController');

    // Rooms
    Route::resource("catalogues/residences/{residence}/rooms", "Admin\RoomController");

    // Roles
    Route::put("roles/{role}/activate", ['as' => 'roles.activate', 'uses' => "Admin\RoleController@activate"]);
    Route::resource("roles", "Admin\RoleController");

    // Moneda
    Route::get('currencies', ['as' => 'currencies.index', 'uses' => 'Admin\CurrencyController@index']);
    Route::get('currencies/create', ['as' => 'currencies.create', 'uses' => 'Admin\CurrencyController@create']);
    Route::post('currencies', ['as' => 'currencies.store', 'uses' => 'Admin\CurrencyController@store']);
    Route::get('currencies/{id}', ['as' => 'currencies.show', 'uses' => 'Admin\CurrencyController@show']);
    Route::get('currencies/{id}/edit', ['as' => 'currencies.edit', 'uses' => 'Admin\CurrencyController@edit']);
    Route::put('currencies/{id}', ['as' => 'currencies.update', 'uses' => 'Admin\CurrencyController@update']);
    Route::delete('currencies/{id}', ['as' => 'currencies.destroy', 'uses' => 'Admin\CurrencyController@destroy']);
});

// public
Route::group(['middleware' => ['auth_client']], function() {
    Route::get('booking', ['as' => 'public.bookings.index', 'uses' => 'BookingController@index']);
    Route::post('booking', ['as' => 'public.bookings.store', 'uses' => 'BookingController@store']);
    Route::get('booking/payment', ['as' => 'public.bookings.payment', 'uses' => 'BookingController@payment']);
    // Pay with conekta
    Route::post('booking/payment', ['as' => 'public.bookings.process_payment', 'uses' => 'BookingController@processPayment']);
    // Personal information
    Route::get('booking/your-info', ['as' => 'public.bookings.your-info', 'uses' => 'BookingController@personalInfo']);

Front/app/Http/Controllers/Admin/ConsumptionCenterController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use Constant;

class ConsumptionCenterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $url = 'api/v1/consumption-centers';
        $params = ['page' => 1];
        if (!empty($request->get('page'))) {
            $params['page'] = $request->get('page');
        }
        $consumptionCenters = $this->get($url . '?' . make_url_params($params), $request);
        $view = 'consumption-centers.index';
        if (!empty($request->get('is-petty-cash'))) {
            $view = 'petty-cashes.index';
        }
        return view($view)
                ->with([
                    'consumptionCenters' => $consumptionCenters,
                    'params' => $params
                ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $title = "Create consumption center";

        return view('consumption-centers.form')->with([
            'formAction'=> route('consumption-centers.store'),
            'formType' => Constant::FORM_CREATE,
            'title' => $title
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make([], []);

        $response = $this->post("api/v1/consumption-centers", $request->only('name'), $request);

        $request->session()->flash('response', [
            'status_code' => $response->status_code,
            'message' => $response->message
        ]);
        if ($response->status_code != 200 && $response->status_code != 201) {
            if (isset($response->errors)) {
                foreach ($response->errors as $key => $messages) {
                    foreach ($messages as $msg) {
                        $validator->errors()->add($key, $msg);
                    }
                }
            }
            return redirect()
                    ->back()
                    ->withInput()
                    ->withErrors($validator);
        }
        return redirect()->route('consumption-centers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id, Request $request)
    {
        $title = "Show consumption center";
        $consumptionCenter = $this->get("api/v1/consumption-centers/$id", $request);
        return view('consumption-centers.form')->with([
            'consumptionCenter' => $consumptionCenter->data,
            'formAction'=> '',
            'formType' => Constant::FORM_SHOW,
            'title' => $title
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, Request $request)
    {
        $title = "Edit consumption center";
        $consumptionCenter = $this->get("api/v1/consumption-centers/$id", $request);
        return view('consumption-centers.form')->with([
            'consumptionCenter' => $consumptionCenter->data,
            'formAction'=> route('consumption-centers.update', ['id' => $consumptionCenter->data->id]),
            'formType' => Constant::FORM_EDIT,
            'title' => $title
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make([], []);

        $response = $this->put("api/v1/consumption-centers/$id", $request->only('name', 'updated_at'), $request);

        $request->session()->flash('response', [
            'status_code' => $response->status_code,
            'message' => $response->message
        ]);
        if ($response->status_code != 200 && $response->status_code != 201) {
            if (isset($response->errors)) {
                foreach ($response->errors as $key => $messages) {
                    foreach ($messages as $msg) {
                        $validator->errors()->add($key, $msg);
                    }
                }
            }
            return redirect()
                    ->back()
                    ->withInput()
                    ->withErrors($validator);
        }
        return redirect()->route('consumption-centers.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
        $response = $this->delete("api/v1/consumption-centers/$id", $request);
        $request->session()->flash('response', [
            'status_code' => $response->status_code,
            'message' => $response->message
        ]);
        return redirect()->back();
    }

    /**
     * Activate / deactivate the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function activate($id, Request $request)
    {
        $response = $this->put("api/v1/consumption-centers/$id/activate", [], $request);
        $request->session()->flash('response', [
            'status_code' => $response->status_code,
            'message' => $response->message
        ]);
        return redirect()->route('consumption-centers.index');
    }
}

Front/resources/views/consumption-centers/form.blade.php
@extends('layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content-header')
    <h1>{{ $title }}</h1>
@endsection

@php
    $readOnly = ($formType === Constant::FORM_SHOW) ? 'readonly' : '';
@endphp

@section('content')
<form id="client-form" action="{{ $formType === Constant::FORM_SHOW ? '#' : $formAction }}" method="POST">
    {{ csrf_field() }}
    @if ($formType === Constant::FORM_EDIT)
        {{ method_field('PUT') }}
        <input type="hidden" name="updated_at" value="{{ $consumptionCenter->updated_at }}" />
    @endif
    <div class="box" style="">
        <div class="box-body">
            <div class="form-group {{ $errors->has('slug') ? 'has-error' : '' }}">
                <label for="name" class="control-label">Name*</label>
                <input id="name" type="text" class="form-control"
                    name="name" value="{{ old('name', isset($consumptionCenter)? $consumptionCenter->name : '') }}" {{ $readOnly }} required>
                <span class="help-block">{{ str_replace('slug', 'name', $errors->first('slug')) }}</span>
            </div>
        </div>
        <div class="box-footer">
            <a class="btn btn-default" href="{{ url()->previous() }}">
                @if ($formType !== Constant::FORM_SHOW)
                    Cancel
                @else
                    Back
                @endif
            </a>
            @if ($formType !== Constant::FORM_SHOW)
                <button class="btn btn-primary" type="submit" name="action">Save</button>
            @else
                <a class="btn btn-primary" href="{{ route('consumption-centers.edit', ['id' => $consumptionCenter->id]) }}">
                    Edit
                </a>
            @endif
        </div>
    </div>

</form>

@endsection

Front/resources/views/consumption-centers/index.blade.php
@extends('layouts.app')

@section('title')
    Consumption centers
@endsection

@section('content-header')
    <h1>Consumption centers</h1>
@endsection

@section('content')
<div class="box">
    <div class="box-header with-border">
        <a href="{{ route('consumption-centers.create') }}" class="btn btn-primary pull-right">New consumption center</a>
    </div>
    <div class="box-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th class="text-center">Status</th>
                    <th class="text-center">View</th>
                    <th class="text-center">Edit</th>
                    <th class="text-center">Delete</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($consumptionCenters->data as $consumptionCenter)
                <tr>
                    <td>{{ $consumptionCenter->name }}</td>
                    <td class="text-center fit">
                        <form action="{{ route('consumption-centers.activate', [ 'id' => $consumptionCenter->id]) }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <button type="submit" class="action-btn table-btn-activate" style="opacity: 1;" title="{{ $consumptionCenter->is_active == 1? 'Deactivate' : 'Activate' }}">
                                <i class="fa fa-flag {{ $consumptionCenter->is_active == 1 ? 'on' : 'off' }}" aria-hidden="true"></i>
                            </button>
                        </form>
                    </td>
                    <td class="text-center fit">
                        <a class="action-btn" href="{{ route('consumption-centers.show', ['id' => $consumptionCenter->id]) }}">
                            <i class="fa fa-search" aria-hidden="true"></i>
                        </a>
                    </td>
                    <td class="text-center fit">
                        <a class="action-btn" href="{{ route('consumption-centers.edit', ['id' => $consumptionCenter->id]) }}">
                            <i class="fa fa-pencil" aria-hidden="true"></i>
                        </a>
                    </td>
                    <td class="text-center fit">
                        <form action="{{ route('consumption-centers.destroy', [ 'id' => $consumptionCenter->id]) }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="action-btn table-btn-destroy">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </button>
                        </form>
                    </td>
                </tr>
                @empty
                    <tr>
                        <td colspan="40">No data</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        {!! Component::pagination(
            10,
            $consumptionCenters->meta->pagination->current_page,
            $consumptionCenters->meta->pagination->total_pages,
            $params
            ) !!}
    </div>
</div>
<script type="text/javascript">
    window.addEventListener('load', function() {
        EXP.initConfirmButton({
            selector: 'button.table-btn-destroy',
            title: "Delete consumption center",
            msg: "This action is going to delete the current consumption center.",
            callback: function(btn) {
                $(btn).parent().submit();
            }
        });

        EXP.initConfirmButton({
            selector: 'button.table-btn-activate',
            title: "Activate/deactivate consumption center",
            msg: "This action is going to activate/deactivate the current consumption center.",
            callback: function(btn) {
                $(btn).parent().submit();
            }
        });
    });
</script>
@endsection