Front/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('booking');
});
Route::get('/admin', function () {
    $user = Auth::user();
    if (empty($user)) {
        return redirect()->route('login');
    }
    switch ($user->authenticatable_type) {
        case 'App\Client':
        case 'App\Agency':
            return redirect()->route('bookings.index');
            break;
        default:
            return redirect()->route('dashboard.index');
    }
});

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
Route::post('/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function() {
    Route::get('dashboard', ['as' => 'dashboard.index', 'uses' => 'Admin\DashboardController@index']);
    Route::post('dashboard/export', ['as' => 'dashboard.export', 'uses' => 'Admin\DashboardController@exportToPDF']);
    Route::get('bookings/count', ['as' => 'bookings.count', 'uses' => 'Admin\BookingController@count']);
    Route::get('bookings/news', ['as' => 'bookings.news', 'uses' => 'Admin\BookingController@newBookings']);
    Route::get('bookings/{booking}/logs', ['as' => 'bookings.logs', 'uses' => 'Admin\BookingController@logs']);
    Route::resource('bookings', 'Admin\BookingController');
    Route::post('bookings/class-status', ['as' => 'bookings.class-status', 'uses' => 'Admin\BookingController@updateClassStatus']);
    Route::post('bookings/export/excel', ['as' => 'bookings.export-excel', 'uses' => 'Admin\BookingController@exportToExel']);
    Route::post('bookings/export/csv', ['as' => 'bookings.export-csv', 'uses' => 'Admin\BookingController@exportToCsv']);
    Route::post('bookings/payments/mark-as-invoiced', ['as' => 'bookings.payments.mark_as_invoiced', 'uses' => 'Admin\BookingController@markPaymentsAsInvoiced']);

    Route::put('commands/{command}/accommodation', ['as' => 'commands.accommodations.update', 'uses' => 'Admin\CommandController@storeAccommodation']);

    Route::resource('clients', 'Admin\ClientController');
    Route::post('clients/export/csv', ['as' => 'clients.csv', 'uses' => 'Admin\ClientController@exportToCsv']);
    // Client credential
    Route::get('clients/{client}/credential', ['as' => 'clients.credential', 'uses' => 'Admin\ClientController@generateCredential']);

    Route::resource('agencies', 'Admin\AgencyController');
    Route::get('/accommodations/scheduler', ['as' => 'accommodations.scheduler', 'uses' => 'Admin\AccommodationController@scheduler']);
    Route::get('/accommodations', ['as' => 'accommodations.index', 'uses' => 'Admin\AccommodationController@index']);

    Route::resource('catalogues/housing', 'Admin\HousingController');
    Route::put('catalogues/housing/{housing}/activate',['as' => 'housing.activate', 'uses' => 'Admin\HousingController@activate']);

    // Housing rooms
    Route::get('catalogues/housing/{housing}/rooms',['as' => 'housing.rooms.index', 'uses' => 'Admin\HousingRoomController@index']);
    Route::post('catalogues/housing/{housing}/rooms',['as' => 'housing.rooms.store', 'uses' => 'Admin\HousingRoomController@store']);
    Route::get('catalogues/housing/{housing}/rooms/create',['as' => 'housing.rooms.create', 'uses' => 'Admin\HousingRoomController@create']);
    Route::get('catalogues/housing/rooms/{room}',['as' => 'housing.rooms.show', 'uses' => 'Admin\HousingRoomController@show']);
    Route::get('catalogues/housing/rooms/{room}/edit',['as' => 'housing.rooms.edit', 'uses' => 'Admin\HousingRoomController@edit']);
    Route::put('catalogues/housing/rooms/{room}',['as' => 'housing.rooms.update', 'uses' => 'Admin\HousingRoomController@update']);
    Route::delete('catalogues/housing/rooms/{room}',['as' => 'housing.rooms.destroy', 'uses' => 'Admin\HousingRoomController@destroy']);
    Route::put('catalogues/housing/rooms/{room}/activate',['as' => 'housing.rooms.activate', 'uses' => 'Admin\HousingRoomController@activate']);

    // Housing room package
    Route::get('catalogues/housing/rooms/{room}/packages',['as' => 'housing.rooms.packages.index', 'uses' => 'Admin\HousingRoomPackageController@index']);
    Route::post('catalogues/housing/rooms/{room}/packages',['as' => 'housing.rooms.packages.store', 'uses' => 'Admin\HousingRoomPackageController@store']);
    Route::get('catalogues/housing/rooms/{room}/packages/create',['as' => 'housing.rooms.packages.create', 'uses' => 'Admin\HousingRoomPackageController@create']);
    Route::get('catalogues/housing/rooms/packages/{housingRoomPackage}',['as' => 'housing.rooms.packages.show', 'uses' => 'Admin\HousingRoomPackageController@show']);
    Route::get('catalogues/housing/rooms/packages/{housingRoomPackage}/edit',['as' => 'housing.rooms.packages.edit', 'uses' => 'Admin\HousingRoomPackageController@edit']);
    Route::put('catalogues/housing/rooms/packages/{housingRoomPackage}',['as' => 'housing.rooms.packages.update', 'uses' => 'Admin\HousingRoomPackageController@update']);
    Route::delete('catalogues/housing/rooms/packages/{housingRoomPackage}',['as' => 'housing.rooms.packages.destroy', 'uses' => 'Admin\HousingRoomPackageController@destroy']);
    Route::put('catalogues/housing/rooms/packages/{housingRoomPackage}/activate',['as' => 'housing.rooms.packages.activate', 'uses' => 'Admin\HousingRoomPackageController@activate']);

    Route::get('reports/{report}', ['as' => 'reports.index',  'uses' => 'Admin\ReportController@index']);
    Route::post('reports/export', ['as' => 'reports.export',  'uses' => 'Admin\ReportController@exportToPDF']);
    Route::resource('users', 'Admin\UserController');

    Route::resource('groups', 'Admin\GroupController');
    Route::resource('schedules', 'Admin\ScheduleController');
    Route::post('schedules/print', ['as' => 'schedules.print', 'uses' => 'Admin\ScheduleController@print']);
    Route::post('schedules/export/csv', ['as' => 'schedules.csv', 'uses' => 'Admin\ScheduleController@exportToCsv']);

    Route::get('import', ['as' => 'import.index', 'uses' => 'Admin\ImportController@index']);
    Route::post('import', ['as' => 'import.store', 'uses' => 'Admin\ImportController@store']);
    Route::get('import/{id}', ['as' => 'import.show', 'uses' => 'Admin\ImportController@show']);

    // Centro de consumo
    Route::resource('consumption-centers', 'Admin\ConsumptionCenterController');
    Route::put('consumption-centers/{consumptionCenter}/activate', ['as' => 'consumption-centers.activate', 'uses' => 'Admin\ConsumptionCenterController@activate']);

    // Caja chica
    Route::resource('petty-cashes', 'Admin\PettyCashController');
    Route::post('petty-cashes/export/csv', ['as' => 'petty-cashes.csv', 'uses' => 'Admin\PettyCashController@exportToCsv']);

    // Room-types
    Route::get('catalogues/room-types', ['as' => 'room-types.index', 'uses' => 'Admin\RoomTypeController@index']);
    Route::get('catalogues/room-types/create', ['as' => 'room-types.create', 'uses' => 'Admin\RoomTypeController@create']);
    Route::post('catalogues/room-types', ['as' => 'room-types.store', 'uses' => 'Admin\RoomTypeController@store']);
    Route::get('catalogues/room-types/{roomType}', ['as' => 'room-types.show', 'uses' => 'Admin\RoomTypeController@show']);
    Route::get('catalogues/room-types/{roomType}/edit', ['as' => 'room-types.edit', 'uses' => 'Admin\RoomTypeController@edit']);
    Route::put('catalogues/room-types/{roomType}', ['as' => 'room-types.update', 'uses' => 'Admin\RoomTypeController@update']);
    Route::delete('catalogues/room-types/{roomType}', ['as' => 'room-types.destroy', 'uses' => 'Admin\RoomTypeController@destroy']);
    Route::put('catalogues/room-types/{roomType}/activate', ['as' => 'room-types.activate', 'uses' => 'Admin\RoomTypeController@activate']);

    // Countries
    Route::get('catalogues/countries', ['as' => 'countries.index', 'uses' => 'Admin\CountryController@index']);
    Route::get('catalogues/countries/create', ['as' => 'countries.create', 'uses' => 'Admin\CountryController@create']);
    Route::post('catalogues/countries', ['as' => 'countries.store', 'uses' => 'Admin\CountryController@store']);
    Route::get('catalogues/countries/{country}', ['as' => 'countries.show', 'uses' => 'Admin\CountryController@show']);
    Route::get('catalogues/countries/{country}/edit', ['as' => 'countries.edit', 'uses' => 'Admin\CountryController@edit']);
    Route::put('catalogues/countries/{country}', ['as' => 'countries.update', 'uses' => 'Admin\CountryController@update']);
    Route::delete('catalogues/countries/{country}', ['as' => 'countries.destroy', 'uses' => 'Admin\CountryController@destroy']);
    Route::put('catalogues/countries/{country}/activate', ['as' => 'countries.activate', 'uses' => 'Admin\CountryController@activate']);
    Route::put('catalogues/countries/{country}/sort', ['as' => 'countries.sort', 'uses' => 'Admin\CountryController@sort']);

    // Courses
    Route::resource('catalogues/courses', 'Admin\CourseController');
    Route::put('catalogues/courses/{package}/activate', ['as' => 'courses.activate', 'uses' => 'Admin\CourseController@activate']);

    // Experiences
    Route::post('catalogues/experiences', ['as' => 'experiences.store', 'uses' => 'Admin\ExperienceController@store']);
    Route::get('catalogues/experiences/create', ['as' => 'experiences.create', 'uses' => 'Admin\ExperienceController@create']);

    // People
    Route::get('catalogues/people', ['as' => 'people.index', 'uses' => 'Admin\PersonController@index']);

Front/app/Http/Controllers/Admin/AgencyController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use Constant;

class AgencyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $agencies = [];
        $params = $this->prepareParams($request, ['page']);
        $url = 'api/v1/agencies';
        $agencies = $this->get($url . '?' . make_url_params($params), $request);

        return view('agencies.index')
            ->with(compact('agencies', 'params'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $formType = Constant::FORM_CREATE;
        $formAction = route('agencies.store');

        return view('agencies.form')
            ->with(compact('formType', 'formAction'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make([], []);
        $data = $request->only('name', 'email', 'password', 'logo', 'code');

        foreach ($data as $k => $v) {
            if (empty($v)) {
                unset($data[$k]);
            }
        }

        $isLogoEmpty = false;
        foreach ($data['logo'] as $v) {
            if (empty($v)) {
                $isLogoEmpty = true;
                break;
            }
        }
        if ($isLogoEmpty) {
            unset($data['logo']);
        }

        $result = $this->storeInApi('api/v1/agencies', $data, $request);
        if($result !== true ) {
            return $result;
        }
        return redirect()->route('agencies.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $formType = Constant::FORM_EDIT;
        $formAction = route('agencies.update', ['id' => $id]);
        $agency = $this->get("api/v1/agencies/$id?include=file", $request)->data;

        return view('agencies.form')
            ->with(compact('agency', 'formType', 'formAction'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->only('updated_at', 'name', 'email', 'password', 'logo', 'code');

        foreach ($data as $k => $v) {
            if (empty($v)) {
                unset($data[$k]);
            }
        }

        $isLogoEmpty = false;
        foreach ($data['logo'] as $v) {
            if (empty($v)) {
                $isLogoEmpty = true;
                break;
            }
        }
        if ($isLogoEmpty) {
            unset($data['logo']);
        }
        // dd($data);

        $result = $this->updateInApi("api/v1/agencies/$id", $data, $request);
        if($result !== true ) {
            return $result;
        }
        return redirect()->route('agencies.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $response = $this->delete("api/v1/agencies/$id", $request);
        $request->session()->flash('response', [
            'status_code' => $response->status_code,
            'message' => $response->message
        ]);
        return redirect()->back();
    }
}

Front/resources/views/agencies/form.blade.php
@extends('layouts.app')

@if ($formType === Constant::FORM_CREATE)
    @section('title', 'Create agency')
@elseif($formType === Constant::FORM_EDIT)
    @section('title', 'Edit agency')
@elseif ($formType === Constant::FORM_SHOW)
    @section('title', 'View agency')
@endif

@section('content-header')
    @if ($formType === Constant::FORM_CREATE)
        <h1>Create agency</h1>
    @elseif ($formType === Constant::FORM_EDIT)
        <h1>Edit agency</h1>
    @elseif ($formType === Constant::FORM_SHOW)
        <h1>View agency</h1>
    @endif
@endsection

@section('content')
    <form action="{{ isset($formAction) ? $formAction : '#' }}" method="post" role="form">
        {{ csrf_field() }}
        @if ($formType === Constant::FORM_EDIT)
            {{ method_field('PUT') }}
            <input type="hidden" name="updated_at" value="{{ $agency->updated_at }}">
        @endif
        <div class="box">
            <div class="box-body">

                <div class="form-group {{ $errors->has('code') ? 'has-error' : '' }}">
                    <label for="code" class="control-label">Code*</label>
                    <input type="text" name="code" id="code" class="form-control" required value="{{ old('code', isset($agency)? $agency->code : '') }}" style="text-transform: uppercase;" maxlength="3">
                    <span class="help-block">{{ $errors->first('code') }}</span>
                </div>

                <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                    <label for="name" class="control-label">Name*</label>
                    <input type="text"name="name" id="name" class="form-control"
                        aria-describedby="help-name" required value="{{ old('name') !== null ?
                            old('name') :
                            (isset($agency->name) ? $agency->name : '') }}">
                    <span id="help-name" class="help-block">{{ $errors->first('name') }}</span>
                </div>

                <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                    <label for="email" class="control-label">Email*</label>
                    <input type="email"name="email" id="email" class="form-control"
                        aria-describedby="help-email" required value="{{ old('email') !== null ?
                            old('email') :
                            (isset($agency->email) ? $agency->email : '') }}">
                    <span id="help-email" class="help-block">{{ $errors->first('email') }}</span>
                </div>

                <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                    <label for="password" class="control-label">Password*</label>
                    <input type="password" name="password" id="password" class="form-control"
                        aria-describedby="help-password" {{ $formType === Constant::FORM_EDIT ? '' : 'required' }}
                        value="{{ old('password') !== null ? old('password') : '' }}">
                    <span id="help-password" class="help-block">{{ $errors->first('password') }}</span>
                </div>

                <div class="form-group {{ $errors->has('logo') ? 'has-error' : '' }}">
                    <label for="phone" class="control-label">Logo*</label>
                    <div>
                        @if (isset($agency->file->data->path))
                            <img src="{{ $agency->file->data->path }}" id="logo" width="300" height="300">
                        @endif
                        <div id="croppie-image" class="hidden"></div>
                        <div class="input-group ">
                            <input type="file" id="file" value="Choose an image" accept="image/*">
                            <input type="hidden" id="file-content" name="logo[contents]" />
                            <input type="hidden" id="file-name" name="logo[name]" />
                        </div>
                    </div>
                    <span class="help-block">{{ empty($errors->first('logo')) ? 'Please, use image(JPG, PNG or GIF) less than 1 MB.' : $errors->first('logo') }}</span>
                </div>

            </div>
            <div class="box-footer">
                <a class="btn btn-default" href="{{ url()->previous() }}">
                    @if ($formType !== Constant::FORM_SHOW)
                        Cancel
                    @else
                        Back
                    @endif
                </a>
                @if ($formType === Constant::FORM_SHOW) {
                    <a class="btn btn-primary" href="{{ route('agencies.edit', ['agency' => $agency->id]) }}">
                        Edit
                    </a>
                @else
                    <button type="submit" class="btn btn-primary">Save</button>
                @endif
            </div>
        </div>
    </form>
@endsection

@section('scripts')
    @parent
    <script>
        var $file = $('#file'),
            $fileContent = $('#file-content'),
            $fileName = $('#file-name'),
            $croppie = $("#croppie-image").croppie({
                viewport: { width: 300, height: 300 },
                boundary: { width: 308, height: 308 },
                showZoomer: false,
                url: ''
            });

        $file.on('change', function(e) {
            var file = this.files[0];

            if (this.files && file) {
                var reader = new FileReader();

                reader.onload = function(ev) {
                    $croppie.croppie('bind', {
                        url: ev.target.result
                    });
                    $fileName.val(file.name);
                    $fileContent.val(ev.target.result.split(',')[1]);
                    $('#logo').addClass('hidden');
                    $('#croppie-image').removeClass('hidden');
                }

                reader.readAsDataURL(file);
            }
        });
        $croppie.on('update', function(e, data) {
            $croppie.croppie('result', {
                type: 'base64'
            }).then(function(d) {
                $fileContent.val(d.split(',')[1]);
            });
        });
    </script>
@endsection

Front/resources/views/agencies/index.blade.php
@extends('layouts.app')

@section('title', 'Agencies')

@section('content-header')
    <h1>Agencies</h1>
@endsection

@section('content')
    @php
        $user = Auth::user();
    @endphp
    <div class="box">
        <div class="box-header with-border">
            @empty ($user->authenticatable_type)
                <a href="{{ route('agencies.create') }}" class="btn btn-primary pull-right">New agency</a>
            @endempty
        </div>
        <div class="box-body table-responsive no-padding">

            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Code</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th class="fit">Edit</th>
                        <th class="fit">Estatus</th>
                        @empty ($user->authenticatable_type)
                            <th class="fit">Delete</th>
                        @endempty
                    </tr>
                </thead>
                <tbody>
                    @forelse ($agencies->data as $a)
                        <tr>
                            <td>{{ $a->code }}</td>
                            <td>{{ $a->name }}</td>
                            <td>{{ $a->email }}</td>
                            <td class="text-center">
                                <a href="{{ route('agencies.edit', ['id' => $a->id]) }}" class="action-btn">
                                    <i class="fa fa-pencil" aria-hidden="true"></i>
                                </a>
                            </td>
                            <td class="text-center">
                                <i class="fa fa-flag {{ $a->is_active == 1 ? 'on' : 'off' }}" aria-hidden="true"></i>
                            </td>
                            @empty ($user->authenticatable_type)
                                <td class="text-center">
                                    <form action="{{ route('agencies.destroy', [ 'id' => $a->id]) }}" method="post">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button type="submit" class="action-btn table-btn-destroy">
                                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                                        </button>
                                    </form>
                                </td>
                            @endempty
                        </tr>
                    @empty
                        <tr>
                            <td colspan="40">No data</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
            @if (isset($agencies->meta))
                {!! Component::pagination(
                    10,
                    $agencies->meta->pagination->current_page,
                    $agencies->meta->pagination->total_pages,
                    $params
                ) !!}
            @endif

        </div>
    </div>
@endsection

@section('scripts')
    @parent
    <script type="text/javascript">
        window.addEventListener('load', function() {
            EXP.initConfirmButton({
                selector: 'button.table-btn-destroy',
                title: "Delete agency",
                msg: "This action is going to delete the current agency.",
                callback: function(btn) {
                    $(btn).parent().submit();
                }
            });
        });
    </script>
@endsection