Front/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('booking');
});
Route::get('/admin', function () {
    $user = Auth::user();
    if (empty($user)) {
        return redirect()->route('login');
    }
    switch ($user->authenticatable_type) {
        case 'App\Client':
        case 'App\Agency':
            return redirect()->route('bookings.index');
            break;
        default:
            return redirect()->route('dashboard.index');
    }
});

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
Route::post('/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function() {
    Route::get('dashboard', ['as' => 'dashboard.index', 'uses' => 'Admin\DashboardController@index']);
    Route::post('dashboard/export', ['as' => 'dashboard.export', 'uses' => 'Admin\DashboardController@exportToPDF']);
    Route::get('bookings/count', ['as' => 'bookings.count', 'uses' => 'Admin\BookingController@count']);
    Route::get('bookings/news', ['as' => 'bookings.news', 'uses' => 'Admin\BookingController@newBookings']);
    Route::get('bookings/{booking}/logs', ['as' => 'bookings.logs', 'uses' => 'Admin\BookingController@logs']);
    Route::resource('bookings', 'Admin\BookingController');
    Route::post('bookings/class-status', ['as' => 'bookings.class-status', 'uses' => 'Admin\BookingController@updateClassStatus']);
    Route::post('bookings/export/excel', ['as' => 'bookings.export-excel', 'uses' => 'Admin\BookingController@exportToExel']);
    Route::post('bookings/export/csv', ['as' => 'bookings.export-csv', 'uses' => 'Admin\BookingController@exportToCsv']);
    Route::post('bookings/payments/mark-as-invoiced', ['as' => 'bookings.payments.mark_as_invoiced', 'uses' => 'Admin\BookingController@markPaymentsAsInvoiced']);

    Route::put('commands/{command}/accommodation', ['as' => 'commands.accommodations.update', 'uses' => 'Admin\CommandController@storeAccommodation']);

    Route::resource('clients', 'Admin\ClientController');
    Route::post('clients/export/csv', ['as' => 'clients.csv', 'uses' => 'Admin\ClientController@exportToCsv']);
    // Client credential
    Route::get('clients/{client}/credential', ['as' => 'clients.credential', 'uses' => 'Admin\ClientController@generateCredential']);

    Route::resource('agencies', 'Admin\AgencyController');
    Route::get('/accommodations/scheduler', ['as' => 'accommodations.scheduler', 'uses' => 'Admin\AccommodationController@scheduler']);
    Route::get('/accommodations', ['as' => 'accommodations.index', 'uses' => 'Admin\AccommodationController@index']);

    Route::resource('catalogues/housing', 'Admin\HousingController');
    Route::put('catalogues/housing/{housing}/activate',['as' => 'housing.activate', 'uses' => 'Admin\HousingController@activate']);

    // Housing rooms
    Route::get('catalogues/housing/{housing}/rooms',['as' => 'housing.rooms.index', 'uses' => 'Admin\HousingRoomController@index']);
    Route::post('catalogues/housing/{housing}/rooms',['as' => 'housing.rooms.store', 'uses' => 'Admin\HousingRoomController@store']);
    Route::get('catalogues/housing/{housing}/rooms/create',['as' => 'housing.rooms.create', 'uses' => 'Admin\HousingRoomController@create']);
    Route::get('catalogues/housing/rooms/{room}',['as' => 'housing.rooms.show', 'uses' => 'Admin\HousingRoomController@show']);
    Route::get('catalogues/housing/rooms/{room}/edit',['as' => 'housing.rooms.edit', 'uses' => 'Admin\HousingRoomController@edit']);
    Route::put('catalogues/housing/rooms/{room}',['as' => 'housing.rooms.update', 'uses' => 'Admin\HousingRoomController@update']);
    Route::delete('catalogues/housing/rooms/{room}',['as' => 'housing.rooms.destroy', 'uses' => 'Admin\HousingRoomController@destroy']);
    Route::put('catalogues/housing/rooms/{room}/activate',['as' => 'housing.rooms.activate', 'uses' => 'Admin\HousingRoomController@activate']);

    // Housing room package
    Route::get('catalogues/housing/rooms/{room}/packages',['as' => 'housing.rooms.packages.index', 'uses' => 'Admin\HousingRoomPackageController@index']);
    Route::post('catalogues/housing/rooms/{room}/packages',['as' => 'housing.rooms.packages.store', 'uses' => 'Admin\HousingRoomPackageController@store']);
    Route::get('catalogues/housing/rooms/{room}/packages/create',['as' => 'housing.rooms.packages.create', 'uses' => 'Admin\HousingRoomPackageController@create']);
    Route::get('catalogues/housing/rooms/packages/{housingRoomPackage}',['as' => 'housing.rooms.packages.show', 'uses' => 'Admin\HousingRoomPackageController@show']);
    Route::get('catalogues/housing/rooms/packages/{housingRoomPackage}/edit',['as' => 'housing.rooms.packages.edit', 'uses' => 'Admin\HousingRoomPackageController@edit']);
    Route::put('catalogues/housing/rooms/packages/{housingRoomPackage}',['as' => 'housing.rooms.packages.update', 'uses' => 'Admin\HousingRoomPackageController@update']);
    Route::delete('catalogues/housing/rooms/packages/{housingRoomPackage}',['as' => 'housing.rooms.packages.destroy', 'uses' => 'Admin\HousingRoomPackageController@destroy']);
    Route::put('catalogues/housing/rooms/packages/{housingRoomPackage}/activate',['as' => 'housing.rooms.packages.activate', 'uses' => 'Admin\HousingRoomPackageController@activate']);

    Route::get('reports/{report}', ['as' => 'reports.index',  'uses' => 'Admin\ReportController@index']);
    Route::post('reports/export', ['as' => 'reports.export',  'uses' => 'Admin\ReportController@exportToPDF']);
    Route::resource('users', 'Admin\UserController');

    Route::resource('groups', 'Admin\GroupController');
    Route::resource('schedules', 'Admin\ScheduleController');
    Route::post('schedules/print', ['as' => 'schedules.print', 'uses' => 'Admin\ScheduleController@print']);
    Route::post('schedules/export/csv', ['as' => 'schedules.csv', 'uses' => 'Admin\ScheduleController@exportToCsv']);

    Route::get('import', ['as' => 'import.index', 'uses' => 'Admin\ImportController@index']);
    Route::post('import', ['as' => 'import.store', 'uses' => 'Admin\ImportController@store']);
    Route::get('import/{id}', ['as' => 'import.show', 'uses' => 'Admin\ImportController@show']);

    // Centro de consumo
    Route::resource('consumption-centers', 'Admin\ConsumptionCenterController');
    Route::put('consumption-centers/{consumptionCenter}/activate', ['as' => 'consumption-centers.activate', 'uses' => 'Admin\ConsumptionCenterController@activate']);

    // Caja chica
    Route::resource('petty-cashes', 'Admin\PettyCashController');
    Route::post('petty-cashes/export/csv', ['as' => 'petty-cashes.csv', 'uses' => 'Admin\PettyCashController@exportToCsv']);

    // Room-types
    Route::get('catalogues/room-types', ['as' => 'room-types.index', 'uses' => 'Admin\RoomTypeController@index']);
    Route::get('catalogues/room-types/create', ['as' => 'room-types.create', 'uses' => 'Admin\RoomTypeController@create']);
    Route::post('catalogues/room-types', ['as' => 'room-types.store', 'uses' => 'Admin\RoomTypeController@store']);
    Route::get('catalogues/room-types/{roomType}', ['as' => 'room-types.show', 'uses' => 'Admin\RoomTypeController@show']);
    Route::get('catalogues/room-types/{roomType}/edit', ['as' => 'room-types.edit', 'uses' => 'Admin\RoomTypeController@edit']);
    Route::put('catalogues/room-types/{roomType}', ['as' => 'room-types.update', 'uses' => 'Admin\RoomTypeController@update']);
    Route::delete('catalogues/room-types/{roomType}', ['as' => 'room-types.destroy', 'uses' => 'Admin\RoomTypeController@destroy']);
    Route::put('catalogues/room-types/{roomType}/activate', ['as' => 'room-types.activate', 'uses' => 'Admin\RoomTypeController@activate']);

    // Countries
    Route::get('catalogues/countries', ['as' => 'countries.index', 'uses' => 'Admin\CountryController@index']);
    Route::get('catalogues/countries/create', ['as' => 'countries.create', 'uses' => 'Admin\CountryController@create']);
    Route::post('catalogues/countries', ['as' => 'countries.store', 'uses' => 'Admin\CountryController@store']);
    Route::get('catalogues/countries/{country}', ['as' => 'countries.show', 'uses' => 'Admin\CountryController@show']);
    Route::get('catalogues/countries/{country}/edit', ['as' => 'countries.edit', 'uses' => 'Admin\CountryController@edit']);
    Route::put('catalogues/countries/{country}', ['as' => 'countries.update', 'uses' => 'Admin\CountryController@update']);
    Route::delete('catalogues/countries/{country}', ['as' => 'countries.destroy', 'uses' => 'Admin\CountryController@destroy']);
    Route::put('catalogues/countries/{country}/activate', ['as' => 'countries.activate', 'uses' => 'Admin\CountryController@activate']);
    Route::put('catalogues/countries/{country}/sort', ['as' => 'countries.sort', 'uses' => 'Admin\CountryController@sort']);

    // Courses
    Route::resource('catalogues/courses', 'Admin\CourseController');
    Route::put('catalogues/courses/{package}/activate', ['as' => 'courses.activate', 'uses' => 'Admin\CourseController@activate']);

    // Experiences
    Route::post('catalogues/experiences', ['as' => 'experiences.store', 'uses' => 'Admin\ExperienceController@store']);
    Route::get('catalogues/experiences/create', ['as' => 'experiences.create', 'uses' => 'Admin\ExperienceController@create']);

    // People
    Route::get('catalogues/people', ['as' => 'people.index', 'uses' => 'Admin\PersonController@index']);

Front/resources/views/clients/credential.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Credential {{ $fullName }}</title>
        <style type="text/css">
            * {
                padding: 0;
                margin: 0;
                box-sizing: border-box;
            }

            .main {
                margin: 30px 15px;
                padding: 10px;
            }

            .credential__background {
                width: 8.6cm;
                height: 5.4cm;
                display: block;
                position: absolute;
                left: 0;
                top: 0;
            }

            .credential__back {
                transform: rotate(180deg);
            }

            .credential__front, .credential__back {
                width: 8.6cm;
                height: 5.4cm;
                position: relative;
            }

            .credential__info {
                position: absolute;
                z-index: 100;
            }

            .credential__info--name, .credential__info--validity {
                left: 122px;
                font-family: sans-serif;
            }

            .credential__info--name {
                font-size: .8em;
                top: 100px;
                color: #3F5AB0;
                font-weight: bold;
            }

            .credential__info--validity {
                top: 147px;
                font-size: .6em;
            }

            .credential__info--photo {
                top: 45px;
                left: 16px;
                width: 90px;
                height: 95px;
                display: block;
            }
        </style>
    </head>
    <body>
        <div class="main">
            <div class="credential">
                <div class="credential__front">
                    <img class="credential__background" src="{{ asset('img/admin/credential_front.jpg') }}" alt="Credential front">
                    @if (!empty($file))
                        <img class="credential__info credential__info--photo" src="{{ $file }}" alt="Client photo">
                    @endif
                    <p class="credential__info credential__info--name">{{ $fullName }}</p>
                    <p class="credential__info credential__info--validity">{{ $validity }}</p>
                </div>
                <div class="credential__back">
                    <img class="credential__background" src="{{ asset('img/admin/credential_back.jpg') }}" alt="Credential back">
                </div>
            </div>
        </div>
    </body>
</html>

Front/resources/views/clients/index.blade.php
@extends('layouts.app')

@section('title')
    Clients
@endsection

@section('content-header')
    <h1>Clients</h1>
@endsection

@section('content')

<div class="box" style="">
    @php
        $user = Auth::user();
    @endphp
    <div class="box-header with-border">
    @empty ($user->authenticatable_type)
        <a href="{{ route('clients.create') }}" class="btn btn-primary pull-right">New client</a>
    @endempty
    </div>
    <div class="box-body">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title h3">Filter by</h2>
            </div>
            <div class="panel-body">
                <form action="{{ url()->full() }}" method="get">
                    <div class="row">
                        <div class="form-group col-sm-6">
                            @php
                                $clientSelected = Request::get('name', '');
                            @endphp
                            <label>Full name</label>
                            <select class="form-control select2" name="name">
                                <option value="">-- Select client name --</option>
                                @foreach ($clientsWithoutPagination->data as $client)
                                    <option value="{{ $client->full_name }}" {{ $clientSelected == $client->full_name? 'selected' : '' }}>{{ $client->full_name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary" name="is_filter" value="true"><i class="fa fa-filter"></i> Filter</button>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
        <div class="" style="margin: 10px 0;">
            <button type="button" class="btn btn-primary pull-right" id="btn-export-to-csv">
                <i class="fa fa-file-excel-o" aria-hidden="true"></i>
                Export to CSV
            </button>
            <div class="clearfix"></div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-hover datatable" data-url-booking-index="{{ route('bookings.index') }}">
                <thead>
                    <tr>
                        <th>First name</th>
                        <th>Last name</th>
                        <th>Email</th>
                        <th class="text-center fit">Commands</th>
                        <th class="text-center fit">Credential</th>
                        <th class="text-center fit">View</th>
                        <th class="text-center fit">Edit</th>
                        @if ($user->authenticatable_type !== 'App\Client')
                            <th class="text-center fit">Delete</th>
                        @endif
                    </tr>
                </thead>
                <tbody>
                    @foreach ($clients->data as $client)
                    <tr data-client-id="{{ $client->id }}" data-url-ajax="{{ route('bookings.index') }}">
                        <td>{{ $client->first_name }}</td>
                        <td>{{ $client->last_name }}</td>
                        <td>{{ $client->email }}</td>
                        <td class="text-center details-control action-btn fit" style="cursor: pointer;">
                            <i class="fa fa-address-card" aria-hidden="true"></i>
                        </td>
                        <td class="text-center" style="cursor: pointer;">
                            <a href="{{ route('clients.credential', ['id' => $client->id]) }}" class="action-btn">
                                <i class="fa fa-id-card-o" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="{{ route('clients.show', ['id' => $client->id]) }}" class="action-btn">
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="{{ route('clients.edit', ['id' => $client->id]) }}" class="action-btn">
                                <i class="fa fa-pencil" aria-hidden="true"></i>
                            </a>
                        </td>
                        @if ($user->authenticatable_type !== 'App\Client')
                            <td class="text-center">
                                <form action="{{ route('clients.destroy', [ 'id' => $client->id]) }}" method="POST">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <button type="submit" class="action-btn table-btn-destroy">
                                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                                    </button>
                                </form>
                            </td>
                        @endif
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        {!! Component::pagination(
            10,
            $clients->meta->pagination->current_page,
            $clients->meta->pagination->total_pages,
            $params
        ) !!}
    </div>
</div>
@endsection

@section('scripts')
    @parent
    <script src="{{ asset('js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('js/sprintf.min.js') }}"></script>
    <script>
        function format(commands, urlBookingIndex) {
            var ret = '<div style="padding: 16px;">';
            var totalCommands = commands.data.length;

            if (totalCommands == 0) {
                ret += 'No data available!'
            }

            // Add packages name
            _.forEach(commands.data, function(command, k) {
                ret += sprintf(
                    '<a href="%s/%s/edit" target="_blank" class="text-color-black">- Command: %s</a>%s',
                    urlBookingIndex,
                    command.id,
                    command.booking_code,
                    (k < (commands.data.length - 1)) ? '<hr>' : ''
                );
            });

            return ret + '</div>';
        }

        $(function() {
            var $dt = $('.datatable');
            var dt = $dt.DataTable({
                paging: false,
                searching: false,
                ordering: false,
                info: false
            });
            $dt.find('tbody').on( 'click', 'tr td.details-control', function () {
                var tr = $(this).closest('tr');
                var row = dt.row(tr);
                var clientId = 0;
                var urlAjax = '';
                var urlBookingIndex = '';
                var commands = null;

                if ( row.child.isShown() ) {
                    tr.removeClass( 'details' );
                    row.child.hide();
                } else {
                    clientId = tr.data('clientId');
                    urlAjax = tr.data('urlAjax');
                    urlBookingIndex = tr.closest('table').data('urlBookingIndex');
                    $.get(sprintf('%s?include=commandCourses&client_id=%s', urlAjax, clientId), function(res) {
                        tr.addClass('details');
                        row.child( format(res, urlBookingIndex) ).show();
                    });
                }
            });

            EXP.initConfirmButton({
                selector: 'button.table-btn-destroy',
                title: "Delete client",
                msg: "This action is going to delete the current client.",
                callback: function(btn) {
                    $(btn).parent().submit();
                }
            });

            EXP.Downloader({
                el: '#btn-export-to-csv',
                url: '{{ route('clients.csv') }}',
                filename: 'clients.csv',
                mimetype: 'application/csv',
            }, function(request) {
                request.send("_token={{ csrf_token() }}");
            });
        });
    </script>
@endsection